project:
  type: website
  output-dir: docs

website:
  title: "SAE Workshop"
  navbar:
    left:
      - href: index.qmd
        text: My Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

