project:
  type: website
  output-dir: docs

website:
  title: "SAE Workshop"
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: Home
        href: index.qmd
      
      - section: Introduction to SAE
        contents: 
        - introduction.qmd
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

