project:
  type: website
  output-dir: docs

website:
  title: "SAE Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: introduction.qmd
        text: Intro to SAE
        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

