project:
  type: website
  output-dir: docs

website:
  title: "SAE Workshop"
  
  sidebar:
    style: "floating"
    search: true
    
    tools:
      - icon: github
        menu:
        - text: Source Code
          href: https://github.com/cpeiretgarcia/sae-workshop-website

    contents:
      - text: Home
        href: index.qmd
      
      - section: Introduction to SAE
        contents: 
        - introduction.qmd
        
      - section: Methods
        contents:
        - methods.qmd

      - section: Applications
        contents:
        - applications.qmd
        
      - section: Practical
        contents:
        - practical.qmd
        
      - section: Summary
        contents:
        - summary.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

